### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by normanhh3** [dylanmei/linqpad-soap-driver#8]
I am connecting to a SOAP 1.2 service endpoint hosted in Tomcat and winding up with a null reference exception in Linqpad when it attempts to generate the proxy to talk to the service.

Any chance you know where I can find the detailed exception stack trace so I can start digging?

**Comment by normanhh3** [comment]
According to this [LinqPad Driver Development document](https://www.linqpad.net/DataContextDrivers.docx) the place to look for the diagnostic logs is: `%localappdata%\linqpad\logs\` which did indeed have the call stack data for the null-reference exception for this driver.

> 4.57.02(AnyCPU) 2017-01-12T09:14:42.8638185-05:00 Custom Data Context Driver - 
> NullReferenceException: Object reference not set to an instance of an object.
>    at Driver.SchemaBuilder.Build(ServiceDescription description, String bindingName, Assembly assembly)
>    at Driver.SoapContextDriver.GetSchemaAndBuildAssembly(IConnectionInfo connectionInfo, AssemblyName assemblyToBuild, String& nameSpace, String& typeName)
>    at LINQPad.SchemaBuilder.GetSchemaAndBuildAssembly(String repositoryData, AssemblyName assemblyToBuild, String& nameSpace, String& typeName, Boolean allowOneToOne, IDictionary`2& sessionData)
> First chance data:
> 
> 4.57.02(AnyCPU) 2017-01-12T09:14:42.8708024-05:00 Error opening DataContext - 
> DisplayToUserException: NullReferenceException - Object reference not set to an instance of an object.
> 
> Server stack trace: 
>    at LINQPad.SchemaBuilder.GetSchemaAndBuildAssembly(String repositoryData, AssemblyName assemblyToBuild, String& nameSpace, String& typeName, Boolean allowOneToOne, IDictionary`2& sessionData)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
> 
> Exception rethrown at [0]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    at LINQPad.SchemaBuilder.GetSchemaAndBuildAssembly(String repositoryData, AssemblyName assemblyToBuild, String& nameSpace, String& typeName, Boolean allowOneToOne, IDictionary`2& sessionData)
>    at LINQPad.DataContextManager.Runner.UpdateSchema(Boolean searchCache, Nullable`1 lastSchemaUpdate)
>    at LINQPad.DataContextManager.Runner.GetDCInfo(SchemaChangeTestMode schemaTestMode)
> First chance data: LINQPad.SchemaBuilder.GetSchemaAndBuildAssembly(repositoryData,assemblyToBuild,nameSpace,typeName,allowOneToOne,sessionData) offset=0xFFFFFFFF
>    -LINQPad.DataContextManager+Runner.UpdateSchema(searchCache,lastSchemaUpdate) offset=0x287
>    -LINQPad.DataContextManager+Runner.GetDCInfo(schemaTestMode) offset=0x163
>    -LINQPad.DataContextManager+Runner+<>c__DisplayClass17.<Start>b__15() offset=0x11

I haven't yet started debugging with a local copy of the code to find out exactly where the null-reference is being thrown from.
